/**
 * El texto del panel de administración, en los dos idiomas, como el resto de la app.
 *
 * Vive aparte de shellCopy porque sólo lo carga el chunk del admin: un usuario común no
 * descarga ni una palabra de acá.
 */

const es = {
  title: 'Panel admin',
  nav: { negocio: 'Negocio', urgencias: 'Urgencias', usuarios: 'Usuarios' },
  backToApp: 'Volver a Vistazo',
  loading: 'Cargando…',
  retry: 'Reintentar',
  genericError: 'No se pudo cargar. Revisá la conexión y reintentá.',
  sectionCrashed: 'Esta sección no se pudo mostrar. El resto del panel sigue andando.',
  signInFirst: 'Iniciá sesión en Vistazo con la cuenta de admin para entrar al panel.',
  forbidden: 'Esta cuenta no tiene acceso al panel.',
  goHome: 'Ir a Vistazo',
  statuses: {
    activa: 'activa',
    trial: 'trial',
    pendiente: 'pendiente',
    pago_fallido: 'pago fallido',
    cancelada: 'cancelada',
    pausada: 'pausada',
    inactiva: 'sin suscripción',
  } as Record<string, string>,
  business: {
    periods: { 7: '7 días', 30: '30 días', 90: '90 días' } as Record<number, string>,
    registered: 'Usuarios registrados',
    registeredDelta: '{n} altas en {days} días · {prev} en los {days} previos',
    pro: 'Suscriptores Pro',
    proDelta: '{n} altas en el período · {trial} en trial',
    mrr: 'Ingreso mensual recurrente',
    mrrHint: '{n} suscripciones activas',
    conversion: 'Conversión de trial a pago',
    conversionDelta: '{sign}{n} pp vs. período previo',
    noConversion: 'Ningún trial terminó en el período',
    signupsTitle: 'Altas por día',
    signupsSub: '{n} en {days} días',
    signupsEmpty: 'Sin altas en el período.',
    collectedTitle: 'Cobrado por mes',
    collectedSub: 'Cobros aprobados, últimos 6 meses',
    collectedEmpty: 'Sin cobros aprobados en los últimos 6 meses.',
    latestTitle: 'Últimas suscripciones',
    latestEmpty: 'Todavía no hay suscripciones.',
    colUser: 'Usuario',
    colStatus: 'Estado',
    colAmount: 'Monto',
    colDate: 'Fecha',
    missingTitle: 'Todavía no se puede medir',
    activeUsers: 'Usuarios activos',
    activeUsersWhy: 'Falta registrar el último ingreso de cada cuenta.',
    aiSpend: 'Gasto en IA',
    aiSpendWhy: 'Falta registrar los tokens de cada llamada.',
    noData: 'Sin datos',
    today: 'hoy',
    daysAgo: 'hace {n} días',
    signupsTip: '{n} altas · {when}',
  },
  urgencies: {
    title: 'Necesita tu atención',
    all: 'Todo',
    severity: { critical: 'Crítico', warning: 'Advertencia', info: 'Info' } as Record<string, string>,
    empty: 'Nada que atender. Los pagos y la IA vienen bien.',
    kinds: {
      orphan_payment: 'Mercado Pago avisó un cobro que no coincide con ninguna cuenta',
      webhook_rejected: '{n} avisos de Mercado Pago rechazados en 24 h',
      payment_pending: 'Pago trabado en Mercado Pago',
      payment_failed: 'Cobro rechazado',
      trial_blocked: '{n} trials frenados: {reason}',
      ai_failing: '"{metric}" falló {n} veces en 24 h',
    } as Record<string, string>,
    orphanDetail: 'Referencia {ref} · aviso {topic}. Buscá la cuenta por el mail del pagador.',
    rejectedDetail: 'Último motivo: {reason}. Si rotaste el secreto, falta actualizar MercadoPago__WebhookSecret.',
    pendingDetail: '{email} · {reason}',
    failedDetail: '{email} · {reason}',
    graceLeft: 'Acceso hasta el {date}',
    trialReasons: {
      ip_used: 'misma IP que otra cuenta',
      network_used: 'misma red que otra cuenta',
      device_used: 'mismo dispositivo que otra cuenta',
      country_not_allowed: 'país no habilitado',
    } as Record<string, string>,
    aiErrors: {
      blocked: 'filtro de seguridad de Gemini',
      quota: 'sin cuota de Google',
      unavailable: 'Google no respondió',
      config: 'clave de IA mal configurada',
      invalid: 'respuesta inválida',
      unknown: 'error desconocido',
    } as Record<string, string>,
    openUser: 'Ver ficha',
    searchUsers: 'Buscar cuenta',
    health: 'Salud de pagos',
    healthSince: 'desde el último deploy',
    received: 'Avisos recibidos',
    accepted: 'Aceptados',
    rejected: 'Rechazados',
    lastAccepted: 'Último aceptado',
    never: 'nunca',
    reconcile: 'Reconciliador',
    reconcileEvery: 'cada {n} min',
    reconcileOff: 'apagado',
    secret: 'Secreto del webhook',
    secretOk: 'configurado',
    secretMissing: 'falta',
    credentials: 'Credenciales',
    credentialsTest: 'de prueba',
    credentialsLive: 'de producción',
    testPayer: 'Pagador forzado',
    testPayerNone: 'no',
  },
  users: {
    searchLabel: 'Buscar cuentas',
    searchPlaceholder: 'Mail, nombre o id de MP',
    results: '{n} cuentas',
    noResults: 'Ninguna cuenta coincide.',
    prev: 'Anterior',
    next: 'Siguiente',
    pick: 'Elegí una cuenta para ver su ficha.',
    joined: 'Se registró el {date}',
    admin: 'Admin',
    usedTrial: 'Usó el trial',
    aiConsent: 'IA aceptada',
    subscription: 'Suscripción',
    noSubscription: 'Nunca tuvo una suscripción.',
    synced: 'Sincronizada {when}',
    neverSynced: 'Nunca sincronizada',
    status: 'Estado',
    plan: 'Plan',
    nextBilling: 'Próximo cobro',
    graceUntil: 'Gracia hasta',
    trialUntil: 'Trial hasta',
    method: 'Medio de pago',
    reference: 'Id en Mercado Pago',
    lastDetail: 'Último motivo',
    sync: 'Consultar a Mercado Pago',
    syncing: 'Consultando…',
    activity: 'Actividad',
    noActivity: 'Sin movimientos registrados.',
    showTech: 'Ver detalle técnico',
    hideTech: 'Ocultar detalle técnico',
    invoices: 'Cobros',
    noInvoices: 'Sin cobros.',
    usage: 'Uso',
    savedAnalyses: 'Análisis guardados',
    sharedStories: 'Historias compartidas',
    aiMetrics: 'Métricas de IA',
    aiFailed: '{n} con error',
    freeUnlocks: 'Desbloqueos gratis',
    trialClaims: 'Trials reclamados',
    history: 'Historial de suscripciones',
  },
  events: {
    checkout: 'Abrió el checkout',
    checkoutTrial: 'Abrió el checkout con 7 días gratis',
    checkoutNoTrial: 'Abrió el checkout sin trial',
    preapproval: 'Mercado Pago actualizó la suscripción',
    paymentApproved: 'Cobro aprobado',
    paymentRejected: 'Cobro rechazado',
    paymentUpdate: 'Mercado Pago informó un cobro',
    cancel: 'Canceló la renovación',
    pause: 'Pausó la suscripción',
    resume: 'Reanudó la suscripción',
    sync: 'Se consultó a Mercado Pago',
    reconcile: 'El reconciliador la puso al día',
    dev: 'Cambio de desarrollo',
    other: 'Movimiento registrado',
  },
  paymentMethods: {
    account_money: 'Dinero en cuenta',
    visa: 'Visa',
    master: 'Mastercard',
    amex: 'American Express',
    debvisa: 'Visa Débito',
    debmaster: 'Mastercard Débito',
    naranja: 'Naranja',
    cabal: 'Cabal',
  } as Record<string, string>,
}

export type AdminCopy = typeof es

const en: AdminCopy = {
  title: 'Admin panel',
  nav: { negocio: 'Business', urgencias: 'Urgent', usuarios: 'Users' },
  backToApp: 'Back to Vistazo',
  loading: 'Loading…',
  retry: 'Retry',
  genericError: 'Could not load. Check the connection and retry.',
  sectionCrashed: 'This section could not be shown. The rest of the panel still works.',
  signInFirst: 'Sign in to Vistazo with the admin account to open the panel.',
  forbidden: 'This account has no access to the panel.',
  goHome: 'Go to Vistazo',
  statuses: {
    activa: 'active',
    trial: 'trial',
    pendiente: 'pending',
    pago_fallido: 'payment failed',
    cancelada: 'cancelled',
    pausada: 'paused',
    inactiva: 'no subscription',
  },
  business: {
    periods: { 7: '7 days', 30: '30 days', 90: '90 days' },
    registered: 'Registered users',
    registeredDelta: '{n} sign-ups in {days} days · {prev} in the previous {days}',
    pro: 'Pro subscribers',
    proDelta: '{n} new in period · {trial} on trial',
    mrr: 'Monthly recurring revenue',
    mrrHint: '{n} active subscriptions',
    conversion: 'Trial to paid',
    conversionDelta: '{sign}{n} pp vs. previous period',
    noConversion: 'No trial ended in the period',
    signupsTitle: 'Sign-ups per day',
    signupsSub: '{n} in {days} days',
    signupsEmpty: 'No sign-ups in the period.',
    collectedTitle: 'Collected per month',
    collectedSub: 'Approved charges, last 6 months',
    collectedEmpty: 'No approved charges in the last 6 months.',
    latestTitle: 'Latest subscriptions',
    latestEmpty: 'No subscriptions yet.',
    colUser: 'User',
    colStatus: 'Status',
    colAmount: 'Amount',
    colDate: 'Date',
    missingTitle: 'Not measurable yet',
    activeUsers: 'Active users',
    activeUsersWhy: 'Last sign-in is not recorded yet.',
    aiSpend: 'AI spend',
    aiSpendWhy: 'Tokens per call are not recorded yet.',
    noData: 'No data',
    today: 'today',
    daysAgo: '{n} days ago',
    signupsTip: '{n} sign-ups · {when}',
  },
  urgencies: {
    title: 'Needs your attention',
    all: 'All',
    severity: { critical: 'Critical', warning: 'Warning', info: 'Info' },
    empty: 'Nothing to handle. Payments and AI look fine.',
    kinds: {
      orphan_payment: 'Mercado Pago reported a charge that matches no account',
      webhook_rejected: '{n} Mercado Pago notifications rejected in 24 h',
      payment_pending: 'Payment stuck at Mercado Pago',
      payment_failed: 'Charge declined',
      trial_blocked: '{n} trials stopped: {reason}',
      ai_failing: '"{metric}" failed {n} times in 24 h',
    },
    orphanDetail: 'Reference {ref} · {topic} notification. Look the account up by the payer email.',
    rejectedDetail: 'Last reason: {reason}. If you rotated the secret, update MercadoPago__WebhookSecret.',
    pendingDetail: '{email} · {reason}',
    failedDetail: '{email} · {reason}',
    graceLeft: 'Access until {date}',
    trialReasons: {
      ip_used: 'same IP as another account',
      network_used: 'same network as another account',
      device_used: 'same device as another account',
      country_not_allowed: 'country not enabled',
    },
    aiErrors: {
      blocked: 'Gemini safety filter',
      quota: 'out of Google quota',
      unavailable: 'Google did not answer',
      config: 'AI key misconfigured',
      invalid: 'invalid answer',
      unknown: 'unknown error',
    },
    openUser: 'Open profile',
    searchUsers: 'Find account',
    health: 'Payments health',
    healthSince: 'since the last deploy',
    received: 'Notifications received',
    accepted: 'Accepted',
    rejected: 'Rejected',
    lastAccepted: 'Last accepted',
    never: 'never',
    reconcile: 'Reconciler',
    reconcileEvery: 'every {n} min',
    reconcileOff: 'off',
    secret: 'Webhook secret',
    secretOk: 'set',
    secretMissing: 'missing',
    credentials: 'Credentials',
    credentialsTest: 'test',
    credentialsLive: 'production',
    testPayer: 'Forced payer',
    testPayerNone: 'no',
  },
  users: {
    searchLabel: 'Search accounts',
    searchPlaceholder: 'Email, name or MP id',
    results: '{n} accounts',
    noResults: 'No account matches.',
    prev: 'Previous',
    next: 'Next',
    pick: 'Pick an account to see its profile.',
    joined: 'Joined {date}',
    admin: 'Admin',
    usedTrial: 'Used the trial',
    aiConsent: 'AI accepted',
    subscription: 'Subscription',
    noSubscription: 'Never had a subscription.',
    synced: 'Synced {when}',
    neverSynced: 'Never synced',
    status: 'Status',
    plan: 'Plan',
    nextBilling: 'Next charge',
    graceUntil: 'Grace until',
    trialUntil: 'Trial until',
    method: 'Payment method',
    reference: 'Mercado Pago id',
    lastDetail: 'Last reason',
    sync: 'Check with Mercado Pago',
    syncing: 'Checking…',
    activity: 'Activity',
    noActivity: 'No activity recorded.',
    showTech: 'Show technical detail',
    hideTech: 'Hide technical detail',
    invoices: 'Charges',
    noInvoices: 'No charges.',
    usage: 'Usage',
    savedAnalyses: 'Saved analyses',
    sharedStories: 'Shared stories',
    aiMetrics: 'AI metrics',
    aiFailed: '{n} failed',
    freeUnlocks: 'Free unlocks',
    trialClaims: 'Trials claimed',
    history: 'Subscription history',
  },
  events: {
    checkout: 'Opened checkout',
    checkoutTrial: 'Opened checkout with 7 free days',
    checkoutNoTrial: 'Opened checkout without trial',
    preapproval: 'Mercado Pago updated the subscription',
    paymentApproved: 'Charge approved',
    paymentRejected: 'Charge declined',
    paymentUpdate: 'Mercado Pago reported a charge',
    cancel: 'Cancelled renewal',
    pause: 'Paused the subscription',
    resume: 'Resumed the subscription',
    sync: 'Checked with Mercado Pago',
    reconcile: 'The reconciler caught it up',
    dev: 'Development change',
    other: 'Activity recorded',
  },
  paymentMethods: {
    account_money: 'Account money',
    visa: 'Visa',
    master: 'Mastercard',
    amex: 'American Express',
    debvisa: 'Visa Debit',
    debmaster: 'Mastercard Debit',
    naranja: 'Naranja',
    cabal: 'Cabal',
  },
}

export const adminCopy = { es, en }
