/**
 * El texto del panel de administración, en los dos idiomas, como el resto de la app.
 *
 * Vive aparte de shellCopy porque sólo lo carga el chunk del admin: un usuario común no
 * descarga ni una palabra de acá.
 */

const es = {
  title: 'Panel admin',
  nav: {
    negocio: 'Negocio',
    urgencias: 'Urgencias',
    usuarios: 'Usuarios',
    cobros: 'Cobros',
    ia: 'IA',
    producto: 'Producto',
    sistema: 'Sistema',
  },
  backToApp: 'Volver a Vistazo',
  loading: 'Cargando…',
  retry: 'Reintentar',
  genericError: 'No se pudo cargar. Revisá la conexión y reintentá.',
  sectionCrashed: 'Esta sección no se pudo mostrar. El resto del panel sigue andando.',
  signInFirst: 'Iniciá sesión en Vistazo con la cuenta de admin para entrar al panel.',
  forbidden: 'Esta cuenta no tiene acceso al panel.',
  goHome: 'Ir a Vistazo',
  periodLabel: 'Período',
  periods: { 7: '7 días', 30: '30 días', 90: '90 días' } as Record<number, string>,
  today: 'hoy',
  daysAgo: 'hace {n} días',
  noData: 'Sin datos',
  prev: 'Anterior',
  next: 'Siguiente',
  exportCsv: 'Exportar CSV',
  exporting: 'Exportando…',
  exportFailed: 'No se pudo exportar. Probá de nuevo.',
  exportNames: { users: 'usuarios', invoices: 'cobros' },
  aiPrices: {
    missing: 'Sin precio',
    missingHint: 'Cargá GoogleAi__InputPricePerMillionUsd y GoogleAi__OutputPricePerMillionUsd para calcularlo.',
  },
  statuses: {
    activa: 'activa',
    trial: 'trial',
    pendiente: 'pendiente',
    pago_fallido: 'pago fallido',
    cancelada: 'cancelada',
    pausada: 'pausada',
    inactiva: 'sin suscripción',
  } as Record<string, string>,
  business: {
    registered: 'Usuarios registrados',
    registeredDelta: '{n} altas en {days} días · {prev} en los {days} previos',
    pro: 'Suscriptores Pro',
    proDelta: '{n} altas en el período · {trial} en trial',
    mrr: 'Ingreso mensual recurrente',
    mrrHint: '{n} suscripciones activas',
    conversion: 'Conversión de trial a pago',
    conversionDelta: '{sign}{n} pp vs. período previo',
    noConversion: 'Ningún trial terminó en el período',
    activeUsers7: 'Activos en 7 días',
    activeUsers30: 'Activos en 30 días',
    activeShare: '{p} de los registrados',
    activeSince: 'Se mide desde esta versión: todavía no entró nadie.',
    aiTokens: 'Tokens de IA del mes',
    aiTokensSub: '{in} de entrada · {out} de salida',
    aiTokensNone: 'Se registran desde esta versión.',
    aiCost: 'Gasto de IA del mes',
    aiCostSub: 'Estimado con los precios configurados',
    signupsTitle: 'Altas por día',
    signupsSub: '{n} en {days} días',
    signupsEmpty: 'Sin altas en el período.',
    signupsTip: '{n} altas · {when}',
    collectedTitle: 'Cobrado por mes',
    collectedSub: 'Cobros aprobados, últimos 6 meses',
    collectedEmpty: 'Sin cobros aprobados en los últimos 6 meses.',
    funnelTitle: 'Embudo de las altas',
    funnelSub: 'Cuentas creadas en los últimos {days} días',
    funnelSteps: {
      registered: 'Se registraron',
      savedAnalysis: 'Guardaron un análisis',
      openedCheckout: 'Abrieron el checkout',
      paid: 'Pagaron',
    },
    funnelEmpty: 'Sin altas en el período.',
    movementsTitle: 'Altas y bajas Pro',
    movementsSub: 'Últimos 6 meses',
    movementsEmpty: 'Sin altas ni bajas Pro en 6 meses.',
    colMonth: 'Mes',
    colStarted: 'Altas',
    colCancelled: 'Bajas',
    colNet: 'Neto',
    latestTitle: 'Últimas suscripciones',
    latestEmpty: 'Todavía no hay suscripciones.',
    colUser: 'Usuario',
    colStatus: 'Estado',
    colAmount: 'Monto',
    colDate: 'Fecha',
  },
  urgencies: {
    title: 'Necesita tu atención',
    all: 'Todo',
    severity: { critical: 'Crítico', warning: 'Advertencia', info: 'Info' } as Record<string, string>,
    empty: 'Nada que atender. Los pagos y la IA vienen bien.',
    kinds: {
      orphan_payment: 'Mercado Pago avisó un cobro que no coincide con ninguna cuenta',
      webhook_rejected: '{n} avisos de Mercado Pago rechazados en 24 h',
      payment_pending: 'Pago trabado en Mercado Pago',
      payment_failed: 'Cobro rechazado',
      trial_blocked: '{n} trials frenados: {reason}',
      trial_ending: 'Trial por vencer',
      ai_failing: '"{metric}" falló {n} veces en 24 h',
    } as Record<string, string>,
    orphanDetail: 'Referencia {ref} · aviso {topic}. Buscá la cuenta por el mail del pagador.',
    rejectedDetail: 'Último motivo: {reason}. Si rotaste el secreto, falta actualizar MercadoPago__WebhookSecret.',
    pendingDetail: '{email} · {reason}',
    failedDetail: '{email} · {reason}',
    graceLeft: 'Acceso hasta el {date}',
    trialEndingDetail: '{email} · vence {when}',
    trialReasons: {
      account_used: 'la cuenta ya usó el trial',
      ip_used: 'misma IP que otra cuenta',
      network_used: 'misma red que otra cuenta',
      device_used: 'mismo dispositivo que otra cuenta',
      country_not_allowed: 'país no habilitado',
    } as Record<string, string>,
    aiErrors: {
      blocked: 'filtro de seguridad de Gemini',
      quota: 'sin cuota de Google',
      unavailable: 'Google no respondió',
      config: 'clave de IA mal configurada',
      invalid: 'respuesta inválida',
      unknown: 'error desconocido',
    } as Record<string, string>,
    openUser: 'Ver ficha',
    searchUsers: 'Buscar cuenta',
    health: 'Salud de pagos',
    healthSince: 'desde el último deploy',
    received: 'Avisos recibidos',
    accepted: 'Aceptados',
    rejected: 'Rechazados',
    rejectedDay: 'Rechazados en 24 h',
    lastAccepted: 'Último aceptado',
    never: 'nunca',
    reconcile: 'Reconciliador',
    reconcileEvery: 'cada {n} min',
    reconcileOff: 'apagado',
    secret: 'Secreto del webhook',
    secretOk: 'configurado',
    secretMissing: 'falta',
    credentials: 'Credenciales',
    credentialsTest: 'de prueba',
    credentialsLive: 'de producción',
    seller: 'Cuenta que cobra',
    sellerUnknown: 'no se pudo consultar',
    testPayer: 'Pagador forzado',
    testPayerNone: 'no',
  },
  users: {
    searchLabel: 'Buscar cuentas',
    searchPlaceholder: 'Mail, nombre o id de MP',
    results: '{n} cuentas',
    noResults: 'Ninguna cuenta coincide.',
    pick: 'Elegí una cuenta para ver su ficha.',
    joined: 'Se registró el {date}',
    lastSeen: 'Último ingreso {when}',
    lastSeenNever: 'Sin ingresos registrados',
    admin: 'Admin',
    usedTrial: 'Usó el trial',
    aiConsent: 'IA aceptada',
    subscription: 'Suscripción',
    noSubscription: 'Nunca tuvo una suscripción.',
    synced: 'Sincronizada {when}',
    neverSynced: 'Nunca sincronizada',
    status: 'Estado',
    plan: 'Plan',
    nextBilling: 'Próximo cobro',
    graceUntil: 'Gracia hasta',
    trialUntil: 'Trial hasta',
    method: 'Medio de pago',
    reference: 'Id en Mercado Pago',
    lastDetail: 'Último motivo',
    sync: 'Consultar a Mercado Pago',
    syncing: 'Consultando…',
    activity: 'Actividad',
    noActivity: 'Sin movimientos registrados.',
    showTech: 'Ver detalle técnico',
    hideTech: 'Ocultar detalle técnico',
    invoices: 'Cobros',
    noInvoices: 'Sin cobros.',
    usage: 'Uso',
    savedAnalyses: 'Análisis guardados',
    sharedStories: 'Historias compartidas',
    aiMetrics: 'Métricas de IA',
    aiFailed: '{n} con error',
    aiTokens: 'Tokens de IA',
    freeUnlocks: 'Desbloqueos gratis',
    trialClaims: 'Trials reclamados',
    history: 'Historial de suscripciones',
    notes: 'Notas internas',
    notesHint: 'Sólo las ve el panel',
    noNotes: 'Sin notas.',
    noteLabel: 'Nueva nota',
    notePlaceholder: 'Ej.: pidió factura, avisó que pagó por transferencia…',
    addNote: 'Guardar nota',
    savingNote: 'Guardando…',
    noteBy: '{author} · {when}',
  },
  invoices: {
    approvedMonth: 'Aprobado este mes',
    approvedMonthSub: 'Desde el 1 del mes, hora argentina',
    total: 'Cobros registrados',
    totalSub: 'Todos los estados',
    rejected: 'Rechazados',
    rejectedSub: 'Desde el primer cobro',
    inFlight: 'En curso',
    inFlightSub: 'Pendientes o reintentando',
    filterLabel: 'Filtrar por estado',
    all: 'Todos',
    empty: 'Ningún cobro con este estado.',
    none: 'Todavía no hay cobros registrados.',
    colDate: 'Fecha',
    colUser: 'Cuenta',
    colStatus: 'Estado',
    colAttempt: 'Intento',
    colAmount: 'Monto',
    statuses: {
      aprobado: 'aprobado',
      rechazado: 'rechazado',
      pendiente: 'pendiente',
      reintentando: 'reintentando',
      devuelto: 'devuelto',
    } as Record<string, string>,
  },
  ai: {
    notTracked: 'Todavía no hay llamadas registradas: el consumo se mide desde esta versión.',
    input: 'Tokens de entrada',
    inputSub: 'Lo que se le manda a Gemini',
    output: 'Tokens de salida',
    outputSub: 'Incluye el razonamiento del modelo',
    cost: 'Costo estimado',
    costSub: 'Últimos {days} días',
    model: 'Modelo',
    tokensTitle: 'Tokens por día',
    tokensSub: 'Entrada + salida',
    tokensEmpty: 'Sin llamadas en el período.',
    tokensTip: '{n} tokens · {when}',
    errorsTitle: 'Errores',
    errorsSub: 'Métricas que terminaron con error',
    errorsEmpty: 'Sin errores en el período.',
    byMetricTitle: 'Por métrica',
    byMetricEmpty: 'Ninguna métrica usó la IA en el período.',
    colMetric: 'Métrica',
    colCalls: 'Llamadas',
    colFailed: 'Con error',
    colTokens: 'Tokens',
  },
  product: {
    analyses: 'Análisis guardados',
    shared: 'Historias compartidas',
    inPeriod: 'En los últimos {days} días',
    live: 'Historias vigentes',
    liveSub: '{n} vistas en total',
    analysesTitle: 'Análisis guardados por día',
    analysesEmpty: 'Sin análisis guardados en el período.',
    analysesTip: '{n} análisis · {when}',
    unlockedTitle: 'Métricas gratis más desbloqueadas',
    aiTitle: 'Métricas de IA más pedidas',
    listEmpty: 'Sin datos en el período.',
  },
  system: {
    integrationsTitle: 'Integraciones',
    instanceTitle: 'Esta instancia',
    environment: 'Entorno',
    version: 'Versión',
    started: 'En marcha desde',
    unknownVersion: 'desconocida',
    states: { ok: 'OK', warn: 'Atención', bad: 'Error', off: 'Apagado' } as Record<string, string>,
    integrations: {
      mercadopago: 'Mercado Pago',
      webhook_secret: 'Secreto del webhook',
      back_url: 'URL de retorno',
      test_payer: 'Pagador forzado',
      google_ai: 'IA de Google',
      ai_prices: 'Precios de la IA',
      recaptcha: 'reCAPTCHA',
    } as Record<string, string>,
    hints: {
      'mercadopago:ok': 'Credenciales de producción.',
      'mercadopago:warn': 'Credenciales de prueba: nadie paga de verdad.',
      'mercadopago:bad': 'Sin credenciales: el checkout no anda.',
      'webhook_secret:ok': 'Configurado.',
      'webhook_secret:bad': 'Falta: cada aviso de Mercado Pago se rechaza.',
      'back_url:ok': 'Pública.',
      'back_url:warn': 'No es pública: Mercado Pago no puede devolver a la gente a la app.',
      'test_payer:ok': 'No forzado.',
      'test_payer:warn': 'Forzado a una cuenta de prueba: sacalo antes de cobrar de verdad.',
      'google_ai:ok': 'Configurada.',
      'google_ai:bad': 'Sin clave: las métricas de IA no andan.',
      'ai_prices:ok': 'Cargados: el gasto de IA se calcula.',
      'ai_prices:off': 'Sin cargar: el gasto de IA no se calcula.',
      'recaptcha:ok': 'Activo.',
      'recaptcha:bad': 'A medio configurar.',
      'recaptcha:off': 'Apagado.',
    } as Record<string, string>,
    denialsTitle: 'Trials negados',
    denialsSub: 'Últimos 30 días, por motivo',
    denialsEmpty: 'Ningún trial negado en 30 días.',
    auditTitle: 'Acciones del panel',
    auditSub: 'Las últimas 50',
    auditEmpty: 'Todavía no hay acciones registradas.',
    colWhen: 'Fecha',
    colAdmin: 'Admin',
    colAction: 'Acción',
    colTarget: 'Cuenta',
    actions: {
      note_added: 'Agregó una nota',
      sync: 'Consultó a Mercado Pago',
      export_users: 'Exportó los usuarios',
      export_invoices: 'Exportó los cobros',
    } as Record<string, string>,
    openTarget: 'Ver ficha',
  },
  events: {
    checkout: 'Abrió el checkout',
    checkoutTrial: 'Abrió el checkout con 7 días gratis',
    checkoutNoTrial: 'Abrió el checkout sin trial',
    preapproval: 'Mercado Pago actualizó la suscripción',
    paymentApproved: 'Cobro aprobado',
    paymentRejected: 'Cobro rechazado',
    paymentUpdate: 'Mercado Pago informó un cobro',
    cancel: 'Canceló la renovación',
    pause: 'Pausó la suscripción',
    resume: 'Reanudó la suscripción',
    sync: 'Se consultó a Mercado Pago',
    reconcile: 'El reconciliador la puso al día',
    dev: 'Cambio de desarrollo',
    other: 'Movimiento registrado',
  },
  paymentMethods: {
    account_money: 'Dinero en cuenta',
    visa: 'Visa',
    master: 'Mastercard',
    amex: 'American Express',
    debvisa: 'Visa Débito',
    debmaster: 'Mastercard Débito',
    naranja: 'Naranja',
    cabal: 'Cabal',
  } as Record<string, string>,
}

export type AdminCopy = typeof es

const en: AdminCopy = {
  title: 'Admin panel',
  nav: {
    negocio: 'Business',
    urgencias: 'Urgent',
    usuarios: 'Users',
    cobros: 'Charges',
    ia: 'AI',
    producto: 'Product',
    sistema: 'System',
  },
  backToApp: 'Back to Vistazo',
  loading: 'Loading…',
  retry: 'Retry',
  genericError: 'Could not load. Check the connection and retry.',
  sectionCrashed: 'This section could not be shown. The rest of the panel still works.',
  signInFirst: 'Sign in to Vistazo with the admin account to open the panel.',
  forbidden: 'This account has no access to the panel.',
  goHome: 'Go to Vistazo',
  periodLabel: 'Period',
  periods: { 7: '7 days', 30: '30 days', 90: '90 days' },
  today: 'today',
  daysAgo: '{n} days ago',
  noData: 'No data',
  prev: 'Previous',
  next: 'Next',
  exportCsv: 'Export CSV',
  exporting: 'Exporting…',
  exportFailed: 'Could not export. Try again.',
  exportNames: { users: 'users', invoices: 'charges' },
  aiPrices: {
    missing: 'No price',
    missingHint: 'Set GoogleAi__InputPricePerMillionUsd and GoogleAi__OutputPricePerMillionUsd to compute it.',
  },
  statuses: {
    activa: 'active',
    trial: 'trial',
    pendiente: 'pending',
    pago_fallido: 'payment failed',
    cancelada: 'cancelled',
    pausada: 'paused',
    inactiva: 'no subscription',
  },
  business: {
    registered: 'Registered users',
    registeredDelta: '{n} sign-ups in {days} days · {prev} in the previous {days}',
    pro: 'Pro subscribers',
    proDelta: '{n} new in period · {trial} on trial',
    mrr: 'Monthly recurring revenue',
    mrrHint: '{n} active subscriptions',
    conversion: 'Trial to paid',
    conversionDelta: '{sign}{n} pp vs. previous period',
    noConversion: 'No trial ended in the period',
    activeUsers7: 'Active in 7 days',
    activeUsers30: 'Active in 30 days',
    activeShare: '{p} of registered users',
    activeSince: 'Measured from this version on: nobody has come back yet.',
    aiTokens: 'AI tokens this month',
    aiTokensSub: '{in} input · {out} output',
    aiTokensNone: 'Recorded from this version on.',
    aiCost: 'AI spend this month',
    aiCostSub: 'Estimated with the configured prices',
    signupsTitle: 'Sign-ups per day',
    signupsSub: '{n} in {days} days',
    signupsEmpty: 'No sign-ups in the period.',
    signupsTip: '{n} sign-ups · {when}',
    collectedTitle: 'Collected per month',
    collectedSub: 'Approved charges, last 6 months',
    collectedEmpty: 'No approved charges in the last 6 months.',
    funnelTitle: 'Sign-up funnel',
    funnelSub: 'Accounts created in the last {days} days',
    funnelSteps: {
      registered: 'Signed up',
      savedAnalysis: 'Saved an analysis',
      openedCheckout: 'Opened checkout',
      paid: 'Paid',
    },
    funnelEmpty: 'No sign-ups in the period.',
    movementsTitle: 'Pro starts and cancellations',
    movementsSub: 'Last 6 months',
    movementsEmpty: 'No Pro starts or cancellations in 6 months.',
    colMonth: 'Month',
    colStarted: 'Started',
    colCancelled: 'Cancelled',
    colNet: 'Net',
    latestTitle: 'Latest subscriptions',
    latestEmpty: 'No subscriptions yet.',
    colUser: 'User',
    colStatus: 'Status',
    colAmount: 'Amount',
    colDate: 'Date',
  },
  urgencies: {
    title: 'Needs your attention',
    all: 'All',
    severity: { critical: 'Critical', warning: 'Warning', info: 'Info' },
    empty: 'Nothing to handle. Payments and AI look fine.',
    kinds: {
      orphan_payment: 'Mercado Pago reported a charge that matches no account',
      webhook_rejected: '{n} Mercado Pago notifications rejected in 24 h',
      payment_pending: 'Payment stuck at Mercado Pago',
      payment_failed: 'Charge declined',
      trial_blocked: '{n} trials stopped: {reason}',
      trial_ending: 'Trial about to end',
      ai_failing: '"{metric}" failed {n} times in 24 h',
    },
    orphanDetail: 'Reference {ref} · {topic} notification. Look the account up by the payer email.',
    rejectedDetail: 'Last reason: {reason}. If you rotated the secret, update MercadoPago__WebhookSecret.',
    pendingDetail: '{email} · {reason}',
    failedDetail: '{email} · {reason}',
    graceLeft: 'Access until {date}',
    trialEndingDetail: '{email} · ends {when}',
    trialReasons: {
      account_used: 'the account already used it',
      ip_used: 'same IP as another account',
      network_used: 'same network as another account',
      device_used: 'same device as another account',
      country_not_allowed: 'country not enabled',
    },
    aiErrors: {
      blocked: 'Gemini safety filter',
      quota: 'out of Google quota',
      unavailable: 'Google did not answer',
      config: 'AI key misconfigured',
      invalid: 'invalid answer',
      unknown: 'unknown error',
    },
    openUser: 'Open profile',
    searchUsers: 'Find account',
    health: 'Payments health',
    healthSince: 'since the last deploy',
    received: 'Notifications received',
    accepted: 'Accepted',
    rejected: 'Rejected',
    rejectedDay: 'Rejected in 24 h',
    lastAccepted: 'Last accepted',
    never: 'never',
    reconcile: 'Reconciler',
    reconcileEvery: 'every {n} min',
    reconcileOff: 'off',
    secret: 'Webhook secret',
    secretOk: 'set',
    secretMissing: 'missing',
    credentials: 'Credentials',
    credentialsTest: 'test',
    credentialsLive: 'production',
    seller: 'Collecting account',
    sellerUnknown: 'could not check',
    testPayer: 'Forced payer',
    testPayerNone: 'no',
  },
  users: {
    searchLabel: 'Search accounts',
    searchPlaceholder: 'Email, name or MP id',
    results: '{n} accounts',
    noResults: 'No account matches.',
    pick: 'Pick an account to see its profile.',
    joined: 'Joined {date}',
    lastSeen: 'Last seen {when}',
    lastSeenNever: 'No visits recorded',
    admin: 'Admin',
    usedTrial: 'Used the trial',
    aiConsent: 'AI accepted',
    subscription: 'Subscription',
    noSubscription: 'Never had a subscription.',
    synced: 'Synced {when}',
    neverSynced: 'Never synced',
    status: 'Status',
    plan: 'Plan',
    nextBilling: 'Next charge',
    graceUntil: 'Grace until',
    trialUntil: 'Trial until',
    method: 'Payment method',
    reference: 'Mercado Pago id',
    lastDetail: 'Last reason',
    sync: 'Check with Mercado Pago',
    syncing: 'Checking…',
    activity: 'Activity',
    noActivity: 'No activity recorded.',
    showTech: 'Show technical detail',
    hideTech: 'Hide technical detail',
    invoices: 'Charges',
    noInvoices: 'No charges.',
    usage: 'Usage',
    savedAnalyses: 'Saved analyses',
    sharedStories: 'Shared stories',
    aiMetrics: 'AI metrics',
    aiFailed: '{n} failed',
    aiTokens: 'AI tokens',
    freeUnlocks: 'Free unlocks',
    trialClaims: 'Trials claimed',
    history: 'Subscription history',
    notes: 'Internal notes',
    notesHint: 'Only the panel sees them',
    noNotes: 'No notes.',
    noteLabel: 'New note',
    notePlaceholder: 'E.g.: asked for an invoice, says they paid by transfer…',
    addNote: 'Save note',
    savingNote: 'Saving…',
    noteBy: '{author} · {when}',
  },
  invoices: {
    approvedMonth: 'Approved this month',
    approvedMonthSub: 'Since the 1st, Argentina time',
    total: 'Charges recorded',
    totalSub: 'All statuses',
    rejected: 'Declined',
    rejectedSub: 'Since the first charge',
    inFlight: 'In flight',
    inFlightSub: 'Pending or retrying',
    filterLabel: 'Filter by status',
    all: 'All',
    empty: 'No charge with this status.',
    none: 'No charges recorded yet.',
    colDate: 'Date',
    colUser: 'Account',
    colStatus: 'Status',
    colAttempt: 'Attempt',
    colAmount: 'Amount',
    statuses: {
      aprobado: 'approved',
      rechazado: 'declined',
      pendiente: 'pending',
      reintentando: 'retrying',
      devuelto: 'refunded',
    },
  },
  ai: {
    notTracked: 'No calls recorded yet: usage is measured from this version on.',
    input: 'Input tokens',
    inputSub: 'What is sent to Gemini',
    output: 'Output tokens',
    outputSub: 'Includes the model reasoning',
    cost: 'Estimated cost',
    costSub: 'Last {days} days',
    model: 'Model',
    tokensTitle: 'Tokens per day',
    tokensSub: 'Input + output',
    tokensEmpty: 'No calls in the period.',
    tokensTip: '{n} tokens · {when}',
    errorsTitle: 'Errors',
    errorsSub: 'Metrics that ended in an error',
    errorsEmpty: 'No errors in the period.',
    byMetricTitle: 'Per metric',
    byMetricEmpty: 'No metric used the AI in the period.',
    colMetric: 'Metric',
    colCalls: 'Calls',
    colFailed: 'Failed',
    colTokens: 'Tokens',
  },
  product: {
    analyses: 'Saved analyses',
    shared: 'Shared stories',
    inPeriod: 'In the last {days} days',
    live: 'Live stories',
    liveSub: '{n} views in total',
    analysesTitle: 'Saved analyses per day',
    analysesEmpty: 'No saved analyses in the period.',
    analysesTip: '{n} analyses · {when}',
    unlockedTitle: 'Most unlocked free metrics',
    aiTitle: 'Most requested AI metrics',
    listEmpty: 'No data in the period.',
  },
  system: {
    integrationsTitle: 'Integrations',
    instanceTitle: 'This instance',
    environment: 'Environment',
    version: 'Version',
    started: 'Running since',
    unknownVersion: 'unknown',
    states: { ok: 'OK', warn: 'Attention', bad: 'Error', off: 'Off' },
    integrations: {
      mercadopago: 'Mercado Pago',
      webhook_secret: 'Webhook secret',
      back_url: 'Return URL',
      test_payer: 'Forced payer',
      google_ai: 'Google AI',
      ai_prices: 'AI prices',
      recaptcha: 'reCAPTCHA',
    },
    hints: {
      'mercadopago:ok': 'Production credentials.',
      'mercadopago:warn': 'Test credentials: nobody pays for real.',
      'mercadopago:bad': 'No credentials: checkout does not work.',
      'webhook_secret:ok': 'Set.',
      'webhook_secret:bad': 'Missing: every Mercado Pago notification is rejected.',
      'back_url:ok': 'Public.',
      'back_url:warn': 'Not public: Mercado Pago cannot send people back to the app.',
      'test_payer:ok': 'Not forced.',
      'test_payer:warn': 'Forced to a test account: remove it before charging for real.',
      'google_ai:ok': 'Set.',
      'google_ai:bad': 'No key: AI metrics do not work.',
      'ai_prices:ok': 'Set: AI spend is computed.',
      'ai_prices:off': 'Not set: AI spend is not computed.',
      'recaptcha:ok': 'On.',
      'recaptcha:bad': 'Half configured.',
      'recaptcha:off': 'Off.',
    },
    denialsTitle: 'Denied trials',
    denialsSub: 'Last 30 days, by reason',
    denialsEmpty: 'No trial denied in 30 days.',
    auditTitle: 'Panel actions',
    auditSub: 'The latest 50',
    auditEmpty: 'No actions recorded yet.',
    colWhen: 'Date',
    colAdmin: 'Admin',
    colAction: 'Action',
    colTarget: 'Account',
    actions: {
      note_added: 'Added a note',
      sync: 'Checked with Mercado Pago',
      export_users: 'Exported users',
      export_invoices: 'Exported charges',
    },
    openTarget: 'Open profile',
  },
  events: {
    checkout: 'Opened checkout',
    checkoutTrial: 'Opened checkout with 7 free days',
    checkoutNoTrial: 'Opened checkout without trial',
    preapproval: 'Mercado Pago updated the subscription',
    paymentApproved: 'Charge approved',
    paymentRejected: 'Charge declined',
    paymentUpdate: 'Mercado Pago reported a charge',
    cancel: 'Cancelled renewal',
    pause: 'Paused the subscription',
    resume: 'Resumed the subscription',
    sync: 'Checked with Mercado Pago',
    reconcile: 'The reconciler caught it up',
    dev: 'Development change',
    other: 'Activity recorded',
  },
  paymentMethods: {
    account_money: 'Account money',
    visa: 'Visa',
    master: 'Mastercard',
    amex: 'American Express',
    debvisa: 'Visa Debit',
    debmaster: 'Mastercard Debit',
    naranja: 'Naranja',
    cabal: 'Cabal',
  },
}

export const adminCopy = { es, en }
