import type { Language } from '../types'

/**
 * Todo el texto visible de la app, en los dos idiomas.
 *
 * Vive fuera de los shells a propósito: desktop y mobile muestran exactamente
 * las mismas palabras, así que una sola copia sirve a los dos y no hay forma
 * de que una pantalla quede con un texto viejo.
 */

export const landingMockupStats = {
  es: [
    { value: '76%', label: 'Fran domina la charla' },
    { value: '00:43', label: 'Pico de mensajes nocturnos' },
    { value: '9', label: 'Mensajes seguidos sin respuesta' },
  ],
  en: [
    { value: '76%', label: 'Fran dominates the chat' },
    { value: '12:43 AM', label: 'Late-night message peak' },
    { value: '9', label: 'Messages in a row with no reply' },
  ],
} as const

export const shellCopy = {
  es: {
    title: { prefix: 'Tu chat también merece su propio', highlight: 'Wrapped' },
    landingSubtitle:
      'Subí un export de WhatsApp y descubrí quién monologuea, quién clava el visto, qué horarios dominan y dónde explota la conversación.',
    heroCaption: 'Privado, visual y un poquito picante.',
    whatItDoesTitle: '¿Para qué sirve?',
    whatItDoesBody:
      'La app procesa el chat en tu navegador, calcula métricas divertidas y guarda solo resultados agregados cuando decidís iniciar sesión. Las dos métricas Pro con IA son la única excepción, y te pedimos permiso antes.',
    trustBadges: ['🔒 Tu chat se procesa en tu navegador', '⚡ Resultados en segundos', '🆓 Empezá gratis, sin tarjeta'],
    marqueeItems: [
      '🚩 Detector de Red Flags',
      '😂 Analizador de risas',
      '🔥 Tono picante',
      '🕐 Reloj biológico',
      '☁️ Nube de palabras',
      '📈 +20 estadísticas',
      '🔒 100% privado',
    ],
    howItWorksTitle: 'Cómo funciona',
    howItWorksSteps: [
      { title: 'Subí tu chat', body: 'Exportá la conversación desde WhatsApp (.txt o .zip) y soltala acá.' },
      { title: 'Se procesa en tu navegador', body: 'Las métricas se calculan ahí mismo: el chat completo nunca se sube.' },
      { title: 'Mirá tu Wrapped', body: 'Recorré tarjetas tipo historia con los datos más divertidos del chat.' },
      { title: 'Desbloqueá lo picante', body: 'Con VIP accedés a red flags, tono picante, sentimiento y mucho más.' },
    ],
    examplesTitle: 'Así se sienten las analíticas',
    examplesSubtitle: 'Estos números son de ejemplo — subí tu chat para ver los tuyos, sin vueltas.',
    demoTag: 'Ejemplo',
    setupWarning:
      'Falta configurar VITE_GOOGLE_CLIENT_ID en el frontend o GoogleAuth:AllowedAudience en el backend.',
    loginHeadline: 'Iniciá sesión para guardar tu Wrapped y desbloquear las métricas Pro',
    loginAfterUpload: 'Tu análisis ya está listo. Si querés guardarlo y ver tu historial, iniciá sesión ahora.',
    uploadTitle: 'Subí un .txt o .zip exportado desde WhatsApp',
    uploadHint: 'Podés subir primero y loguearte después. El procesamiento sigue siendo local.',
    saveInfo: 'El backend guarda solo el JSON agregado del análisis, nunca el texto crudo del chat.',
    uploadCta: 'Subir archivo',
    startNow: 'Probar ahora',
    vipOn: 'VIP activo',
    vipOff: 'VIP bloqueado',
    savedTitle: 'Historial guardado',
    noSaved: 'Todavía no hay análisis guardados para este usuario.',
    openSaved: 'Abrir',
    chatSummaryTitle: 'Resumen del chat',
    logout: 'Cerrar sesión',
    processing: 'Procesando archivo...',
    analyzing: 'Analizando tu chat...',
    analyzingAi: 'Analizando las métricas Pro con IA...',
    saving: 'Guardando análisis...',
    loggingIn: 'Iniciando sesión...',
    overlaySubtitle: 'Aguardá unos minutos mientras procesamos la información.',
    aiPartialError:
      'No pudimos procesar algunas métricas con IA. El resto de tu Wrapped está completo — probá de nuevo en unos instantes.',
    ai: {
      failedTitle: 'No pudimos analizar esta métrica con IA',
      reasons: {
        quota: 'Nos quedamos sin cupo de IA por un momento.',
        unavailable: 'La IA no respondió a tiempo.',
        blocked: 'La IA no pudo evaluar estos mensajes.',
        invalid: 'La IA devolvió una respuesta inesperada.',
        config: 'El análisis con IA no está configurado en el servidor.',
        default: 'No pudimos procesar la solicitud con IA.',
      },
      retry: 'Volver a analizar',
      retryIn: 'Vas a poder reintentar en {time}',
      retrying: 'Analizando...',
      needsUpload: 'Subí el chat de nuevo para reintentar',
      consentTitle: 'Métrica con IA',
      consentBody: 'Activá el análisis con IA para ver esta métrica sin falsos positivos.',
      consentCta: 'Activar análisis con IA',
      unavailableTitle: 'IA no disponible',
      unavailableBody: 'Esta instalación todavía no tiene configurado el análisis con IA.',
      pendingTitle: 'Analizando con IA',
      pendingBody: 'Estamos revisando los mensajes marcados. Tarda unos segundos.',
    },
    consent: {
      eyebrow: 'Un permiso, una sola vez',
      title: 'Análisis con IA para dos métricas Pro',
      body:
        'El Detector de Red Flags y El Tono Picante usan filtros de palabras que se equivocan seguido: sin IA, "la comida estaba caliente" cuenta como mensaje subido de tono. La IA revisa esos mensajes marcados y descarta los que no corresponden.',
      bullets: [
        'Solo se envían los mensajes que ya pasaron el filtro de palabras, recortados y con un par de líneas de contexto.',
        'No viajan nombres: cada participante aparece como una letra.',
        'El resto del chat se sigue procesando en tu navegador y nunca sale de tu dispositivo.',
        'El resultado se guarda una sola vez por chat: no se vuelve a analizar ni a cobrar.',
      ],
      accept: 'Activar y analizar',
      decline: 'Ahora no',
      working: 'Activando...',
    },
    manageSubscription: 'Gestionar suscripción',
    vipPopover: {
      eyebrow: 'Métricas Pro',
      title: 'Desbloqueá VIP',
      close: 'Cerrar',
      signInPrompt: 'Iniciá sesión con tu cuenta de Google para suscribirte.',
      signInCta: 'Iniciar sesión',
    },
    subscriptionPage: {
      eyebrow: 'Cuenta',
      title: 'Suscripción',
      lead: 'Gestioná tu plan Pro: beneficios, facturación y cancelación.',
      backToApp: 'Volver a Vistazo',
      signInPrompt: 'Iniciá sesión con tu cuenta de Google para suscribirte y ver el estado de tu cuenta.',
      signInCta: 'Iniciar sesión',
      close: 'Cerrar',
      statuses: {
        pendiente: 'Pendiente de pago',
        trial: 'Prueba gratis',
        activa: 'Activa',
        pago_fallido: 'Pago rechazado',
        pausada: 'Pausada',
        cancelada: 'Cancelada',
        inactiva: 'Sin suscripción',
      },
      statusHints: {
        pendiente: 'Falta completar el pago en Mercado Pago. Podés retomarlo cuando quieras.',
        trial: 'Tenés acceso Pro completo. Si cancelás antes de que termine, no se te cobra nada.',
        activa: 'Se renueva sola todos los meses. La podés cancelar cuando quieras.',
        pago_fallido: 'No pudimos cobrar tu tarjeta. Mercado Pago va a reintentar; mientras tanto mantenés el acceso.',
        pausada: 'No se van a hacer cobros nuevos. Conservás el acceso hasta que termine el período pago.',
        cancelada: 'No se renueva más. Conservás el acceso hasta que termine el período que ya pagaste.',
        inactiva: 'No tenés una suscripción activa.',
      },
      currentPlanTitle: 'Tu plan',
      perMonth: 'por mes',
      freeTrialBadge: '7 días gratis',
      trialEndsOn: 'La prueba termina el',
      renewsOn: 'Próximo cobro',
      endsOn: 'Acceso hasta el',
      graceUntil: 'Acceso garantizado hasta el',
      paymentMethod: 'Medio de pago',
      startedOn: 'Comenzó el',
      lastPayment: 'Último pago',
      cancelCta: 'Cancelar renovación',
      cancelConfirmTitle: '¿Cancelar la renovación automática?',
      cancelConfirmBody:
        'No se te vuelve a cobrar. Mantenés el acceso Pro hasta el {date}, y podés volver a suscribirte cuando quieras.',
      cancelConfirmYes: 'Sí, cancelar',
      cancelConfirmNo: 'Volver',
      refreshCta: 'Actualizar estado',
      refreshing: 'Actualizando...',
      cancelling: 'Cancelando...',
      billedBy: 'Renovación automática',
      autoRenewOn: 'Activada',
      autoRenewOff: 'Desactivada',
      adminNote: 'Tenés acceso Pro por ser administrador, no por una suscripción paga.',
      devNote: 'Suscripción simulada desde el panel local. No corresponde a un pago real.',
      paymentsDisabled: 'Los pagos todavía no están configurados en el servidor.',
      plansTitle: 'Planes disponibles',
      planName: 'Plan mensual',
      planDurationLabel: 'Duración',
      planDurationValue: 'Se renueva automáticamente cada mes',
      planAccessLabel: 'Acceso',
      planAccessValue: 'Todas las métricas Pro, activo apenas se confirma el pago',
      planTrialNote:
        '✨ Tu primera suscripción incluye 7 días de prueba gratis. Cancelá antes de que termine y no se te cobra nada.',
      planBenefitsLabel: 'Qué incluye',
      planBenefits: [
        'Detector de Red Flags y Tono Picante, verificados con IA',
        'Sentimiento, reloj biológico y el resto de las métricas Pro',
        'Desglose completo por integrante en cada tarjeta',
        'Historial ilimitado de chats guardados',
      ],
      buyCta: 'Comprar',
      buyTrialCta: 'Empezar con 7 días gratis',
      trialUnavailable: 'La semana gratis ya fue usada.',
      trialReasons: {
        account_used: 'Esta cuenta ya la aprovechó.',
        ip_used: 'Ya se usó desde esta conexión.',
        network_used: 'Ya se usó desde esta red.',
        device_used: 'Ya se usó desde este dispositivo.',
        country_not_allowed: 'No está disponible en tu país.',
      },
      cardStepTitle: 'Método de pago',
      cardStepBack: 'Volver',
      cardCheckout: {
        missingKey: 'Los pagos todavía no están configurados en el servidor.',
        loading: 'Cargando el formulario de pago...',
        tokenMissing: 'Por ahora las suscripciones solo funcionan con tarjeta de crédito o débito — elegí esa opción para continuar.',
        securedBy: 'Pago procesado de forma segura por Mercado Pago',
      },
      submitting: 'Confirmando con Mercado Pago...',
      genericError: 'No pudimos procesar el pago. Probá de nuevo.',
      successTitle: '¡Listo!',
      successTrialBody: 'Arrancó tu semana gratis. Te avisamos antes del primer cobro.',
      successActiveBody: 'Tu suscripción Pro ya está activa.',
      successCta: 'Entendido',
      invoicesTitle: 'Historial de pagos',
      noInvoices: 'Todavía no hay cobros registrados.',
      invoiceStatuses: {
        aprobado: 'Aprobado',
        rechazado: 'Rechazado',
        pendiente: 'Pendiente',
        reintentando: 'Reintentando',
        devuelto: 'Devuelto',
      },
      invoicePeriod: 'Período {from} — {to}',
      invoiceAttempt: 'Intento {n}',
      historyTitle: 'Historial de suscripciones',
      noHistory: 'Todavía no hay suscripciones registradas.',
      eventsTitle: 'Actividad de la cuenta',
      noEvents: 'Sin movimientos registrados.',
    },
    dev: {
      badge: 'local',
      aiOn: 'IA activada',
      aiOff: 'IA desactivada',
      aiOnHint: 'Se consultan las métricas con IA al importar un chat. Click para desactivar y no gastar tokens.',
      aiOffHint: 'No se consulta la IA al importar un chat. Click para volver a activarla.',
      vipOn: 'Activar suscripción',
      vipOff: 'Desactivar suscripción',
      vipHint: 'Simula una suscripción Pro sin pasar por Mercado Pago.',
      signInFirst: 'Iniciá sesión para usar este atajo.',
      dragHint: 'Arrastrá para mover · doble click para volver a la esquina',
    },
    account: 'Cuenta',
    subscription: 'Suscripción',
    participants: 'Participantes',
    messages: 'Mensajes',
    generatedAt: 'Generado',
    loadError: 'No pude completar la acción.',
    login: 'Iniciar sesión',
    backToLanding: 'Volver a la landing',
    seeMore: 'Ver más',
    close: 'Cerrar',
    detailTitle: 'Desglose completo',
    breakdownTitle: 'Por integrante',
    showMore: 'Mostrar más',
    unlock: 'Desbloquear VIP',
    searchPlaceholder: 'Buscar una palabra…',
    metricsTitle: 'Tu Wrapped completo',
    metricsSubtitle: 'Cada tarjeta tiene un resultado directo. Las bloqueadas se destapan con VIP.',
    savePromptTitle: 'Guardá este Wrapped',
    savePromptBody: 'Iniciá sesión con Google para no perderlo y volver a verlo cuando quieras.',
    reprocessHint: 'Este análisis se guardó sin acceso VIP. Volvé a subir el chat para ver el detalle completo desbloqueado.',
    whyTitle: 'Qué podés descubrir',
    whyCards: [
      {
        icon: '🗣️',
        title: 'Quién domina la charla',
        body: 'Rachas de mensajes seguidos, quién escribe más y quién sobrevive con monosílabos.',
      },
      {
        icon: '🌙',
        title: 'Cuándo se prende el chat',
        body: 'Horarios pico, búhos vs. madrugadores, y los días que hicieron explotar la conversación.',
      },
      {
        icon: '🚩',
        title: 'Lo que nadie se anima a preguntar',
        body: 'Demoras, silencios, red flags y tono picante — desbloqueado con VIP.',
      },
    ],
    footerPrivacy:
      'Tus mensajes se procesan en tu navegador y el chat nunca se sube entero. Solo guardamos métricas agregadas cuando iniciás sesión. Con Pro, y únicamente si lo autorizás, dos métricas envían los mensajes ya marcados por el filtro —recortados y sin nombres— para que una IA los revise.',
    footerRights: 'Hecho con demasiado jajaja.',
    /* Textos que sólo existen en el shell de mobile: pestañas, hoja de subida,
       modo historia. Viven acá y no adentro de los componentes, para que sigan
       la misma regla que el resto — un solo lugar, los dos idiomas. */
    mobile: {
      tabs: { home: 'Inicio', metrics: 'Métricas', history: 'Historial', account: 'Cuenta' },
      openMenu: 'Abrir menú',
      closeMenu: 'Cerrar',
      uploadAction: 'Subir chat',
      drawer: { myWrapped: 'Mi Wrapped', savedHistory: 'Historial guardado', language: 'Idioma', privacy: 'Privacidad' },
      home: { recent: 'Últimos', seeAll: 'Ver todos', empty: 'Todavía no analizaste ningún chat.' },
      upload: {
        eyebrow: 'Nuevo análisis',
        pick: 'Elegí el archivo',
        formats: '.txt o .zip exportado de WhatsApp',
        browse: 'Buscar en el teléfono',
        howTo: 'Cómo exportarlo desde WhatsApp',
        steps: [
          { title: 'Abrí el chat en WhatsApp', body: 'El que quieras analizar, grupal o individual.', warn: false },
          { title: 'Tocá ⋮ · Más · Exportar chat', body: 'En iPhone es el nombre del chat arriba · Exportar chat.', warn: false },
          { title: 'Elegí «Sin archivos multimedia»', body: 'Es el paso que más se saltea. Con multimedia el archivo pesa de más y las fotos no se usan para nada.', warn: true },
          { title: 'Guardá el .txt o .zip en el teléfono', body: 'WhatsApp te ofrece compartirlo — guardalo en Archivos o Descargas.', warn: false },
          { title: 'Volvé acá y tocá la zona de arriba', body: 'Elegís el archivo que guardaste y listo.', warn: false },
        ],
        privacy: 'El archivo se procesa en tu teléfono. Sólo se guardan las métricas agregadas, nunca el texto del chat.',
      },
      list: { metricsCount: 'métricas', proCount: 'Pro', lockedCount: 'bloqueadas', tabList: 'Lista', tabStory: 'Historia' },
      sheet: { next: 'Siguiente métrica', backToList: 'Volver a la lista', prev: 'Métrica anterior', highlights: 'Momentos destacados' },
      story: {
        detail: 'Ver detalle',
        share: 'Compartir',
        exit: 'Salir del recorrido',
        prev: 'Anterior',
        next: 'Siguiente',
        outroTitle: 'métricas Pro te están esperando',
        outroMore: 'y {n} más',
        outroCta: 'Desbloquear VIP',
        copied: 'Copiado',
        shareTag: 'Mi Wrapped de {chat}, en Vistazo',
      },
      account: { signedInAs: 'Sesión iniciada como', noSubscription: 'Sin suscripción' },
    },
  },
  en: {
    title: { prefix: 'Your chat deserves its own', highlight: 'Wrapped' },
    landingSubtitle:
      'Upload a WhatsApp export and uncover who monologues, who leaves you on seen, which hours dominate, and when the conversation explodes.',
    heroCaption: 'Private, visual, and a little spicy.',
    whatItDoesTitle: 'What is it for?',
    whatItDoesBody:
      'The app processes the chat in your browser, computes playful metrics, and only stores aggregated results once you decide to sign in. The two AI-powered Pro metrics are the single exception, and we ask first.',
    trustBadges: ['🔒 Your chat is processed in your browser', '⚡ Results in seconds', '🆓 Start free, no card needed'],
    marqueeItems: [
      '🚩 Red Flag Detector',
      '😂 Laugh Analyzer',
      '🔥 Spicy Tone',
      '🕐 Body Clock',
      '☁️ Word Cloud',
      '📈 20+ stats',
      '🔒 100% private',
    ],
    howItWorksTitle: 'How it works',
    howItWorksSteps: [
      { title: 'Upload your chat', body: 'Export the conversation from WhatsApp (.txt or .zip) and drop it here.' },
      { title: "It's processed in your browser", body: 'Metrics are computed right there — the full chat is never uploaded.' },
      { title: 'See your Wrapped', body: 'Swipe through story-style cards with the most fun stats from the chat.' },
      { title: 'Unlock the spicy stuff', body: 'VIP gets you red flags, spicy tone, sentiment, and a lot more.' },
    ],
    examplesTitle: 'This is how the analytics feel',
    examplesSubtitle: "These numbers are just an example — upload your chat to see your own, no strings attached.",
    demoTag: 'Example',
    setupWarning:
      'VITE_GOOGLE_CLIENT_ID in the frontend or GoogleAuth:AllowedAudience in the backend is still missing.',
    loginHeadline: 'Sign in to save your Wrapped and unlock the Pro metrics',
    loginAfterUpload: 'Your analysis is ready. Sign in now if you want to save it and keep a history.',
    uploadTitle: 'Upload a WhatsApp-exported .txt or .zip',
    uploadHint: 'You can upload first and sign in later. Processing still happens locally.',
    saveInfo: 'The backend stores only aggregated JSON results, never the raw chat text.',
    uploadCta: 'Upload file',
    startNow: 'Try it now',
    vipOn: 'VIP active',
    vipOff: 'VIP locked',
    savedTitle: 'Saved history',
    noSaved: 'There are no saved analyses for this user yet.',
    openSaved: 'Open',
    chatSummaryTitle: 'Chat summary',
    logout: 'Sign out',
    processing: 'Processing file...',
    analyzing: 'Analyzing your chat...',
    analyzingAi: 'Analyzing the Pro metrics with AI...',
    saving: 'Saving analysis...',
    loggingIn: 'Signing in...',
    overlaySubtitle: 'Please wait a few minutes while we process the information.',
    aiPartialError:
      "We couldn't process some metrics with AI. The rest of your Wrapped is complete — try again in a moment.",
    ai: {
      failedTitle: "We couldn't analyze this metric with AI",
      reasons: {
        quota: 'We ran out of AI credit for a moment.',
        unavailable: "The AI didn't answer in time.",
        blocked: "The AI couldn't evaluate these messages.",
        invalid: 'The AI returned an unexpected answer.',
        config: 'AI analysis is not configured on the server.',
        default: "We couldn't process the AI request.",
      },
      retry: 'Analyze again',
      retryIn: 'You can retry in {time}',
      retrying: 'Analyzing...',
      needsUpload: 'Upload the chat again to retry',
      consentTitle: 'AI-powered metric',
      consentBody: 'Turn on AI analysis to see this metric without false positives.',
      consentCta: 'Turn on AI analysis',
      unavailableTitle: 'AI unavailable',
      unavailableBody: 'This installation does not have AI analysis configured yet.',
      pendingTitle: 'Analyzing with AI',
      pendingBody: 'We are reviewing the flagged messages. It takes a few seconds.',
    },
    consent: {
      eyebrow: 'One permission, just once',
      title: 'AI analysis for two Pro metrics',
      body:
        'The Red Flag Detector and The Spicy Tone rely on keyword filters that get it wrong often: without AI, "the food was hot" counts as a suggestive message. The AI reviews those flagged messages and drops the ones that do not belong.',
      bullets: [
        'Only the messages that already passed the keyword filter are sent, trimmed and with a couple of context lines.',
        'No names travel: each participant shows up as a letter.',
        'The rest of the chat is still processed in your browser and never leaves your device.',
        'The result is stored once per chat: it is never analyzed — or billed — twice.',
      ],
      accept: 'Turn on and analyze',
      decline: 'Not now',
      working: 'Turning on...',
    },
    manageSubscription: 'Manage subscription',
    vipPopover: {
      eyebrow: 'Pro metrics',
      title: 'Unlock VIP',
      close: 'Close',
      signInPrompt: 'Sign in with Google to subscribe.',
      signInCta: 'Sign in',
    },
    subscriptionPage: {
      eyebrow: 'Account',
      title: 'Subscription',
      lead: 'Manage your Pro plan: benefits, billing, and cancellation.',
      backToApp: 'Back to Vistazo',
      signInPrompt: 'Sign in with Google to subscribe and see your account status.',
      signInCta: 'Sign in',
      close: 'Close',
      statuses: {
        pendiente: 'Payment pending',
        trial: 'Free trial',
        activa: 'Active',
        pago_fallido: 'Payment declined',
        pausada: 'Paused',
        cancelada: 'Cancelled',
        inactiva: 'No subscription',
      },
      statusHints: {
        pendiente: 'The payment has not been completed on Mercado Pago yet. You can pick it up any time.',
        trial: "You have full Pro access. Cancel before it ends and you won't be charged a thing.",
        activa: 'It renews automatically every month. You can cancel whenever you want.',
        pago_fallido: "We couldn't charge your card. Mercado Pago will retry; you keep access meanwhile.",
        pausada: 'No new charges will be made. You keep access until the paid period ends.',
        cancelada: "It won't renew. You keep access until the period you already paid for ends.",
        inactiva: "You don't have an active subscription.",
      },
      currentPlanTitle: 'Your plan',
      perMonth: 'per month',
      freeTrialBadge: '7 days free',
      trialEndsOn: 'Trial ends on',
      renewsOn: 'Next charge',
      endsOn: 'Access until',
      graceUntil: 'Access guaranteed until',
      paymentMethod: 'Payment method',
      startedOn: 'Started on',
      lastPayment: 'Last payment',
      cancelCta: 'Cancel renewal',
      cancelConfirmTitle: 'Cancel automatic renewal?',
      cancelConfirmBody:
        "You won't be charged again. You keep Pro access until {date}, and you can resubscribe any time.",
      cancelConfirmYes: 'Yes, cancel',
      cancelConfirmNo: 'Go back',
      refreshCta: 'Refresh status',
      refreshing: 'Refreshing...',
      cancelling: 'Cancelling...',
      billedBy: 'Automatic renewal',
      autoRenewOn: 'On',
      autoRenewOff: 'Off',
      adminNote: 'You have Pro access as an administrator, not through a paid subscription.',
      devNote: 'Subscription simulated from the local panel. It does not correspond to a real payment.',
      paymentsDisabled: 'Payments are not configured on the server yet.',
      plansTitle: 'Available plans',
      planName: 'Monthly plan',
      planDurationLabel: 'Duration',
      planDurationValue: 'Renews automatically every month',
      planAccessLabel: 'Access',
      planAccessValue: 'Every Pro metric, active as soon as the payment is confirmed',
      planTrialNote:
        "✨ Your first subscription includes a 7-day free trial. Cancel before it ends and you won't be charged anything.",
      planBenefitsLabel: "What's included",
      planBenefits: [
        'Red Flag Detector and Spicy Tone, verified with AI',
        'Sentiment, body clock, and every other Pro metric',
        'Full per-participant breakdown on every card',
        'Unlimited saved chat history',
      ],
      buyCta: 'Buy',
      buyTrialCta: 'Start with 7 days free',
      trialUnavailable: 'The free week has already been used.',
      trialReasons: {
        account_used: 'This account already took it.',
        ip_used: 'It was already used from this connection.',
        network_used: 'It was already used from this network.',
        device_used: 'It was already used from this device.',
        country_not_allowed: 'It is not available in your country.',
      },
      cardStepTitle: 'Payment method',
      cardStepBack: 'Back',
      cardCheckout: {
        missingKey: 'Payments are not configured on the server yet.',
        loading: 'Loading the payment form...',
        tokenMissing: 'Subscriptions only work with a credit or debit card for now — pick that option to continue.',
        securedBy: 'Payment securely processed by Mercado Pago',
      },
      submitting: 'Confirming with Mercado Pago...',
      genericError: "We couldn't process the payment. Please try again.",
      successTitle: "You're in!",
      successTrialBody: "Your free week just started. We'll warn you before the first charge.",
      successActiveBody: 'Your Pro subscription is now active.',
      successCta: 'Got it',
      invoicesTitle: 'Payment history',
      noInvoices: 'No charges recorded yet.',
      invoiceStatuses: {
        aprobado: 'Approved',
        rechazado: 'Declined',
        pendiente: 'Pending',
        reintentando: 'Retrying',
        devuelto: 'Refunded',
      },
      invoicePeriod: 'Period {from} — {to}',
      invoiceAttempt: 'Attempt {n}',
      historyTitle: 'Subscription history',
      noHistory: 'No subscriptions recorded yet.',
      eventsTitle: 'Account activity',
      noEvents: 'No activity recorded.',
    },
    dev: {
      badge: 'local',
      aiOn: 'AI on',
      aiOff: 'AI off',
      aiOnHint: 'AI metrics run when a chat is imported. Click to turn them off and stop spending tokens.',
      aiOffHint: 'The AI is not called when a chat is imported. Click to turn it back on.',
      vipOn: 'Activate subscription',
      vipOff: 'Deactivate subscription',
      vipHint: 'Simulates a Pro subscription without going through Mercado Pago.',
      signInFirst: 'Sign in to use this shortcut.',
      dragHint: 'Drag to move · double-click to snap back to the corner',
    },
    account: 'Account',
    subscription: 'Subscription',
    participants: 'Participants',
    messages: 'Messages',
    generatedAt: 'Generated',
    loadError: 'I could not complete the action.',
    login: 'Sign in',
    backToLanding: 'Back to landing',
    seeMore: 'See more',
    close: 'Close',
    detailTitle: 'Full breakdown',
    breakdownTitle: 'By participant',
    showMore: 'Show more',
    unlock: 'Unlock VIP',
    searchPlaceholder: 'Search a word…',
    metricsTitle: 'Your full Wrapped',
    metricsSubtitle: 'Every card shows a straight-to-the-point result. Locked ones unlock with VIP.',
    savePromptTitle: 'Save this Wrapped',
    savePromptBody: "Sign in with Google so you don't lose it — come back to it whenever you want.",
    reprocessHint: 'This analysis was saved without VIP access. Re-upload the chat to see the full unlocked detail.',
    whyTitle: 'What you can discover',
    whyCards: [
      {
        icon: '🗣️',
        title: 'Who dominates the chat',
        body: 'Back-to-back streaks, who writes the most, and who survives on one-word replies.',
      },
      {
        icon: '🌙',
        title: 'When the chat comes alive',
        body: 'Peak hours, night owls vs. early birds, and the days that made the conversation explode.',
      },
      {
        icon: '🚩',
        title: 'The stuff nobody asks about out loud',
        body: 'Delays, silences, red flags, and spicy tone — unlocked with VIP.',
      },
    ],
    footerPrivacy:
      'Your messages are processed in your browser and the chat is never uploaded in full. We only store aggregated metrics once you sign in. With Pro, and only if you authorize it, two metrics send the messages already flagged by the keyword filter — trimmed and without names — for an AI to review.',
    footerRights: 'Made with way too much "hahaha".',
    mobile: {
      tabs: { home: 'Home', metrics: 'Metrics', history: 'History', account: 'Account' },
      openMenu: 'Open menu',
      closeMenu: 'Close',
      uploadAction: 'Upload chat',
      drawer: { myWrapped: 'My Wrapped', savedHistory: 'Saved history', language: 'Language', privacy: 'Privacy' },
      home: { recent: 'Recent', seeAll: 'See all', empty: "You haven't analyzed any chat yet." },
      upload: {
        eyebrow: 'New analysis',
        pick: 'Choose the file',
        formats: '.txt or .zip exported from WhatsApp',
        browse: 'Browse your phone',
        howTo: 'How to export it from WhatsApp',
        steps: [
          { title: 'Open the chat in WhatsApp', body: 'Whichever one you want to analyze, group or one-on-one.', warn: false },
          { title: 'Tap ⋮ · More · Export chat', body: "On iPhone it's the chat name at the top · Export chat.", warn: false },
          { title: 'Pick "Without media"', body: 'This is the step people skip. With media the file is much heavier and the photos are never used.', warn: true },
          { title: 'Save the .txt or .zip on your phone', body: 'WhatsApp offers to share it — save it to Files or Downloads.', warn: false },
          { title: 'Come back and tap the area above', body: 'Pick the file you saved and you are done.', warn: false },
        ],
        privacy: 'The file is processed on your phone. Only aggregated metrics are stored, never the chat text.',
      },
      list: { metricsCount: 'metrics', proCount: 'Pro', lockedCount: 'locked', tabList: 'List', tabStory: 'Story' },
      sheet: { next: 'Next metric', backToList: 'Back to the list', prev: 'Previous metric', highlights: 'Highlights' },
      story: {
        detail: 'See detail',
        share: 'Share',
        exit: 'Exit the story',
        prev: 'Previous',
        next: 'Next',
        outroTitle: 'Pro metrics are waiting for you',
        outroMore: 'and {n} more',
        outroCta: 'Unlock VIP',
        copied: 'Copied',
        shareTag: 'My Wrapped of {chat}, on Vistazo',
      },
      account: { signedInAs: 'Signed in as', noSubscription: 'No subscription' },
    },
  },
} as const

export type ShellCopy = (typeof shellCopy)[Language]
